<h1>Detalhes do cliente</h1>
<table class="table">
    <tr>
        <th>
            id Cliente
        <th>
        <td>
            <?=$arrayClients['idClient']?>
        <td>
    </tr>
    <tr>
        <th>
            Nome
        <th>
        <td>
            <?=$arrayClients['name']?>
        <td>
    </tr>
    <tr>
        <th>
            Email
        <th>
        <td>
            <?=$arrayClients['email']?>
        <td>
    </tr>
    <tr>
        <th>
            Telefone
        <th>
        <td>
            <?=$arrayClients['phone']?>
        <td>
    </tr>
    <tr>
        <th>
            Endereço
        <th>
        <td>
            <?=$arrayClients['address']?>
        <td>
    </tr>
</table>